CREATE TABLE IF NOT EXISTS match (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  winner_id INTEGER DEFAULT NULL,
  mode INTEGER NOT NULL,
  status INTEGER DEFAULT 0
);
